import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import "./globals.css";
import { ModalProvider } from "@/context/ModalContext";
import { Toaster } from "sonner";

const poppins = Poppins({ subsets: ['latin'], weight: ["100", "200", "300", "400", "500", "600", "700"] })

export const metadata: Metadata = {
  title: "Swa pify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} scroll-smooth`}
      >
          <Toaster closeButton position="top-center" expand={true} richColors />

        <ModalProvider>
          {children}
        </ModalProvider>
      </body>
    </html>
  );
}
